### PR TITLE
Increase caller skip when converting zap to bark

### PR DESCRIPTION
**Pull request by jkanywhere**
Converting a zap logger to a bark logger adds a frame to the call stack.
Adjust caller skip accordingly, so file and line number are reported
properly when zap logger is configured with `AddCaller`.

### CODE REVIEW

**Comment by jkanywhere** [comment]
A barkified zap logger will now have correct file and line annotations if and only if the original zap logger had caller enabled. I'm not turning on the caller with this change.

From what I can tell, open source bark does not support adding caller information to any log. Therefore I don't think the bark -> zap case is relevant.

**Comment by prashantv** [comment]
It is definitely relevant, here's a very simple test:
```go
func TestPrashant(t *testing.T) {
       logger, err := zap.NewDevelopment()
       require.NoError(t, err)
       logger.Info("hi")

       barker := zbark.Barkify(logger)
       barker.Info("hi2")

       l2 := zbark.Zapify(barker)
       l2.Info("hi3")
 }
```

The output is:
```
2018-02-12T13:51:11.854-0800	INFO	zbark/barkify_test.go:46	hi
2018-02-12T13:51:11.854-0800	INFO	zbark/barkify_test.go:49	hi2
2018-02-12T13:51:11.854-0800	INFO	testing/testing.go:746	hi3
```

Notice how the caller changed for "hi3" -- that's because we add a caller skip going one way, but don't remove that caller skip when going back.

**Comment by jkanywhere** [comment]
I pushed a second commit with tests and changes as you suggested.
Tests start originally with an observable zap logger.

When starting with a bark logger, in my experience, zapified logs will not be annotated with caller file or line number because the underlying logrus  logger doesn't support it. Is there something I am missing?
```go
package bark_test

import (
	"testing"

	"github.com/sirupsen/logrus"
	"github.com/uber-common/bark"
	"github.com/uber-common/bark/zbark"

	"go.uber.org/zap"
)

func TestJkline(t *testing.T) {
	b := bark.NewLoggerFromLogrus(logrus.New())
	z := zbark.Zapify(b).WithOptions(zap.AddCaller())

	b.Info("hello from bark logger")
	z.Info("hello from zapified logger")
}
```
generates output
```
$ go test -v --run TestJkline
=== RUN   TestJkline
INFO[0000] hello from bark logger                       
INFO[0000] hello from zapified logger                   
--- PASS: TestJkline (0.00s)
PASS
ok  	github.com/uber-common/bark	0.020s
```

**Comment by jkanywhere** [comment]
[Travis](https://travis-ci.org/uber-common/bark/builds/347091451) reports success for Go 1.7, 1.8, 1.9 and failure for Go:Tip.

Should I be concerned?

**Comment by jkanywhere** [comment]
close/open to trigger travis rebuild.

**Comment by prashantv** [comment]
The builds are failing because `zap` now requires Go 1.9 or higher,
```
../../../go.uber.org/zap/field.go:33: syntax error: unexpected = in type declaration
```

We'll need to change bark to only test on 1.9 and 1.10 to match zap. @jkanywhere Can you open a separate PR to update the Travis configuration?

**Comment by jkanywhere** [comment]
Yes. https://github.com/uber-common/bark/pull/19

**Comment by jkanywhere** [comment]
https://golang.org/doc/go1.10 states
> Stack traces no longer include implicit wrapper functions (previously marked <autogenerated>), unless a fault or panic happens in the wrapper itself. As a result, skip counts passed to functions like Caller should now always match the structure of the code as written, rather than depending on optimization decisions and implementation details.

I'll consider the ramifications of that later.

**Comment by prashantv** [comment]
> Apparently caller skip adjustment is no longer needed in go 1.10.
> We can revert this when we drop support for 1.9.

I don't understand why the change to remove compiler-generated frames would affect frames added explicit by our wrappers.

**Comment by jkanywhere** [comment]
> I don't understand why the change to remove compiler-generated frames would affect frames added explicit by our wrappers.

I don't understand either, just going with what the test cases show.

**Pull request merged**
